repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: no-commit-to-branch
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.7
  hooks:
  - id: ruff-check
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-check
    args: [--preview, --select=CPY]
  - id: ruff-format
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.20.0
  hooks:
  - id: pyproject-fmt
- repo: https://github.com/biomejs/pre-commit
  rev: v2.4.8
  hooks:
  - id: biome-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.19.1
  hooks:
  - id: mypy
    args: [--config-file=pyproject.toml, .]
    pass_filenames: false
    additional_dependencies:
    - anndata>=0.12
    - array-api-compat>=1.13
    - dask>=2026.1
    - h5py>=3.15
    - numba>=0.63
    - packaging>=26
    - pytest>=9
    - pytest-codspeed>=4.3
    - scikit-learn>=1.8
    - scipy-stubs>=1.17
    - sphinx>=9
    - types-docutils>=0.22
    - zarr>=3.1
ci:
  autoupdate_commit_msg: 'ci: pre-commit autoupdate'
  skip:
  - mypy  # too big
