# SPDX-License-Identifier: MPL-2.0
class IRBuilder:
    def load(self, value: Value) -> Value: ...

class Value: ...
class Constant(Value): ...
class NamedValue(Value): ...
class Instruction(NamedValue): ...
