from collections.abc import Iterable

from llvmlite.ir import IRBuilder  # type: ignore[import-untyped]
from numba.core.base import BaseContext  # type: ignore[import-untyped]

class PythonAPI:
    def __init__(self, context: BaseContext, builder: IRBuilder) -> None: ...
    def incref(self, value: object) -> None: ...
    def decref(self, value: object) -> None: ...
    def serialize_object(self, obj: object) -> object: ...
    def unserialize(self, structptr: object) -> object: ...
    def object_getattr_string(self, obj: object, attr: str) -> object: ...
    def call_function_objargs(self, func: object, args: Iterable[object]) -> object: ...
